# BART Parking {#BARTparking }

#### Keywords {-}

BART, Public Transit, Commuting, Parking

## Parking Issues.

Bart, otherwise known as Bay Area Rapid Transit, is the transportation infrastructural backbone of the Bay Area, with 429,000 [@noauthor_bartfactsheet_nodate] commuters each weekday.  A major issue riders have to deal with is a shortage of parking, which can fill up as early as 6:30 am – 7:00 am on weekday mornings [@noauthor_barts_nodate].  Building additional parking comes with its own set of hurdles, such as designated land, permits, and a large sunk cost.  My proposal outlines a few alternative ideas Bart can utilize to address its parking shortage.  Bart can start by studying user patterns to observe how people get to the station, where they park, and which alternative methods they use when Bart parking is full to determine feasible alternatives for commuters to get to and from their primary stations.  The goal of this proposal is to see if it is possible to make the Bart system more accessible for daily commuters by addressing the lack of available weekday parking spaces at Bart stations.  

## Carpooling – a Solution.

To help gather location data, Bart will need its riders to download their app so Bart can pull and track user’s location data to map out commute patterns and identify groups of daily commuters to effectively focus on.  Bart will try to get as a high an app user base as possible to have as much data as possible to analyze, and can incentive people to download the app through small incentives such as Bart credit via clipper card.   If there is not system wide adoption of their app, they will focus on users who have downloaded the app and publish the benefits of the app outlined below which will further incentivize people to download their app.   As they gather and analyze their user’s location data, Bart can match riders with others who take similar routes to and from the station at similar times.  I’ve outlined three ideas Bart can implement using this data.

My first idea is for Bart to further incentivize carpooling to the station for morning commuters.  Parking space is the scarce resource here, so anything Bart can do to optimize the number of riders using their limited parking space will help maximize the number of riders that are able to use Bart.  I propose that Bart create a “carpool only” lot that will be open only to cars with +3 people in the mornings.  They can implement tier pricing so that the more riders come in one car, the less expensive parking will be, making it free for cars with 5 or more riders.  

To prevent people from taking advantage of this discounted parking without using Bart, such as by a person working in Oakland near the station who wants to use the carpool parking deal to save money but has no intention of riding the train, Bart can charge regular parking fees to those who use their carpool lot and issue a Bart credit that expires at the end of that same day.  This way, the carpool lot will only be discounted for those riding the train.  The entry to the carpool lot will be monitored by an agent, and the credits will be delivered by swiping the clipper cards of all carpoolers in the vehicle at the lot entrance.

A second idea which can run concurrently with the first is for Bart to partner with Uber to promote users ridesharing to reach the stations.  The easiest way to achieve this is to make Uberpools for commutes to/from Bart stations payable via Clipper card.  
Uber will be incentivized to pair with Bart since it will increase people’s dependence on Uber as a mode of transportation and help build their brand.  Bart can target riders who have short commutes but still use the parking lots, as this will capture those that will have a fairly inexpensive Uber ride.  Bart can provide financial incentives to daily commuters to rideshare by integrating Clipper as a form of payment for Uberpools and delivering credits on users Bart rides that expire a few hours after completing an Uberpool ride.  The goal is for Uberpool to be less expensive than parking at the station so commuters will choose to use this alternative naturally.  This will free up parking spots for riders who live further from stations since Uberpool won’t be an affordable option for them. 

A third idea is for Bart to have a mini-bus that uses Microtransit routing to pick up/drop off regular commuters during peak times [@noauthor_microtransit_nodate].  The mini-bus will use the data gathered from the app to have dynamic routes, with drop off and pick up locations adjusting based on current ridership.  The bus will need to charge just under the parking cost for round-trip fare and can also ensure that ridership is only for Bart commuters by charging for the bus on Clipper and providing a discounted morning Bart commute.


```{r experimental,echo=F,results='asis',eval=F}
data.table::fread(‘http://www.greenberg-art.com/.Toons/.Toons,%20Calif/qqxsgBartParking.gif’) %>% stargazer::stargazer(type = 'html',title = 'Something from W241 Experiments and Causality')
```

## Making the System Function

The last thing Bart should do is raise prices for their single occupant vehicle parkers by $2-$3, since increased parking costs will incentivize drivers to try and use one of the alternatives mentioned above and will also help fund these ideas.  This is reasonable to expect from the riders since they will now have 3 alternatives to reach the station (carpool, Uberpool, Bart mini-bus).  Bart can also publish the full cost of parking, inclusive of vehicle mileage cost which is currently rated at 74 cents/mile [@noauthor_aaa_2017] which will further help push some drivers to not drive themselves to the station.

Bart will initially have to invest into this program, giving discounts to incentivize riders to download Bart’s app, rebuilding parts of the parking structure to accommodate a larger carpool lot, and purchasing the mini-buses, and will additionally need to subsidize carpoolers through discounted parking rates, Uberpool, and their mini-bus operation cost while ridership climbs to a critical mass volume.  The increased cost of parking and boost in Bart ridership due to greater accessibility will increase overall revenue and fund my proposed ideas.  
